GET http://localhost:8080/teams

### Fetch all teams 

GET http://localhost:8080/teams/N1PnDQYt4OdFEscmhg9feMIbHpI2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUwM2E2ODg3YWU3ZjNkMTAyNzNjNjRiMDU3ZTY1MzE1MWUyOTBiNzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNjU0MzA2NywidXNlcl9pZCI6Ik4xUG5EUVl0NE9kRkVzY21oZzlmZU1JYkhwSTIiLCJzdWIiOiJOMVBuRFFZdDRPZEZFc2NtaGc5ZmVNSWJIcEkyIiwiaWF0IjoxNzI3MDU5NzkzLCJleHAiOjE3MjcwNjMzOTMsImVtYWlsIjoicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.RLlLq1ixjAnQOFAhEKyqjyvSMIsFj_KILz-qi8FUnKHK19O_iPk_nfKfgAAbXNkFr_Bfaq8MlnzVVTHUdjrj6-Ra1LFt8cf2FzA3jQJbWjaAWwEdjnYASgBoZjnOzatnlgAcvKdANUQc41TFajw3gVrQgNjP-qqIFgi0604v6BBpiJWWgUu4tRdLIxtnE4jO0kgd_JO2D65SF9mt9Sur3PwrekOjO5R8Pwd1k77xRJylbxrB85NJ5VjpxXFKX75rINWO7Mq2bw8VpqHxfp6rx5u8W9FB5_wLtK6EgNKJX1vnPEB2wBFkA8-dPMUXksEw1VnB4u1RMqisdLGW64Ol8A
{
   "teamId": "N1PnDQYt4OdFEscmhg9feMIbHpI2"
}
### Create Team

POST http://localhost:8080/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUwM2E2ODg3YWU3ZjNkMTAyNzNjNjRiMDU3ZTY1MzE1MWUyOTBiNzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNjU0MzA2NywidXNlcl9pZCI6Ik4xUG5EUVl0NE9kRkVzY21oZzlmZU1JYkhwSTIiLCJzdWIiOiJOMVBuRFFZdDRPZEZFc2NtaGc5ZmVNSWJIcEkyIiwiaWF0IjoxNzI3MDU5NzkzLCJleHAiOjE3MjcwNjMzOTMsImVtYWlsIjoicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.RLlLq1ixjAnQOFAhEKyqjyvSMIsFj_KILz-qi8FUnKHK19O_iPk_nfKfgAAbXNkFr_Bfaq8MlnzVVTHUdjrj6-Ra1LFt8cf2FzA3jQJbWjaAWwEdjnYASgBoZjnOzatnlgAcvKdANUQc41TFajw3gVrQgNjP-qqIFgi0604v6BBpiJWWgUu4tRdLIxtnE4jO0kgd_JO2D65SF9mt9Sur3PwrekOjO5R8Pwd1k77xRJylbxrB85NJ5VjpxXFKX75rINWO7Mq2bw8VpqHxfp6rx5u8W9FB5_wLtK6EgNKJX1vnPEB2wBFkA8-dPMUXksEw1VnB4u1RMqisdLGW64Ol8A
Content-Type: application/json

{
   "teamName": "Team 1",
   "invitations": ["pavol@pavol.com", "pavol.slovak@gmail.com"],
   "members": [
     { "id": "N1PnDQYt4OdFEscmhg9feMIbHpI2", "color": "#FF5733" }
   ],
   "weekSchedule": [
        {
            "day": "Mon",
            "shifts": [
                {
                    "memberId": "N1PnDQYt4OdFEscmhg9feMIbHpI2",
                    "startTime": "08:00",
                    "endTime": "12:00"
                },
                {
                    "memberId": "N1PnDQYt4OdFEscmhg9feMIbHpI2",
                    "startTime": "12:00",
                    "endTime": "16:00"
                }
            ]
        }  
    ],
   "createdBy": { "id": "N1PnDQYt4OdFEscmhg9feMIbHpI2" },
   "createdAt": "2021-07-22T15:00:00.000Z",
   "updatedAt": "2021-07-22T15:00:00.000Z"
}

### Fetch teams where user is a member
GET http://localhost:8080/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUwM2E2ODg3YWU3ZjNkMTAyNzNjNjRiMDU3ZTY1MzE1MWUyOTBiNzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNjU0MzA2NywidXNlcl9pZCI6Ik4xUG5EUVl0NE9kRkVzY21oZzlmZU1JYkhwSTIiLCJzdWIiOiJOMVBuRFFZdDRPZEZFc2NtaGc5ZmVNSWJIcEkyIiwiaWF0IjoxNzI3MDU5NzkzLCJleHAiOjE3MjcwNjMzOTMsImVtYWlsIjoicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.RLlLq1ixjAnQOFAhEKyqjyvSMIsFj_KILz-qi8FUnKHK19O_iPk_nfKfgAAbXNkFr_Bfaq8MlnzVVTHUdjrj6-Ra1LFt8cf2FzA3jQJbWjaAWwEdjnYASgBoZjnOzatnlgAcvKdANUQc41TFajw3gVrQgNjP-qqIFgi0604v6BBpiJWWgUu4tRdLIxtnE4jO0kgd_JO2D65SF9mt9Sur3PwrekOjO5R8Pwd1k77xRJylbxrB85NJ5VjpxXFKX75rINWO7Mq2bw8VpqHxfp6rx5u8W9FB5_wLtK6EgNKJX1vnPEB2wBFkA8-dPMUXksEw1VnB4u1RMqisdLGW64Ol8A
Content-Type: application/json

### Find User by ID:
GET http://localhost:8080/users/Dv3gXinnlbSSs3CQqRKqe8zsJpP2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUwM2E2ODg3YWU3ZjNkMTAyNzNjNjRiMDU3ZTY1MzE1MWUyOTBiNzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNjU0MzA2NywidXNlcl9pZCI6Ik4xUG5EUVl0NE9kRkVzY21oZzlmZU1JYkhwSTIiLCJzdWIiOiJOMVBuRFFZdDRPZEZFc2NtaGc5ZmVNSWJIcEkyIiwiaWF0IjoxNzI3MTM1NjYzLCJleHAiOjE3MjcxMzkyNjMsImVtYWlsIjoicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YL83gdj-ClkOAwjPYUEwnMObCGfguAd0Z3OrSTzHFmEcsisFv2A4vntL0BLPm_sVeemTG7XC0UkRC0ksgLBZKGAydqPqWldSjuX3HkwWZflf-l6s_ldS1EaUsGfOE8iS1-eSp_MdNK-wTxCrywiCEaHS0ee2mcUtIHr4ff-f_fx0as-Yp8Zb20FEjGBOI0q5Bxqvx_vauYifMT_TWWMd2mQxBujXYF5fAqrsGmHkxDXTzLVHClhHzwnNDDIkh6tzHzRHSTlUaKlyOjDr6_GVTSVYnBVEWvgvYMo8BloVDXgdTSAhiXYSjzIqgyhg_29bugS8zAb628bAoE_EYVhs3w
Content-Type: application/json


### Fetch members of a team
GET http://localhost:8080/teams/66f0da566827cf0f477fac8d
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUwM2E2ODg3YWU3ZjNkMTAyNzNjNjRiMDU3ZTY1MzE1MWUyOTBiNzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNjU0MzA2NywidXNlcl9pZCI6Ik4xUG5EUVl0NE9kRkVzY21oZzlmZU1JYkhwSTIiLCJzdWIiOiJOMVBuRFFZdDRPZEZFc2NtaGc5ZmVNSWJIcEkyIiwiaWF0IjoxNzI3MTM1NjYzLCJleHAiOjE3MjcxMzkyNjMsImVtYWlsIjoicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.YL83gdj-ClkOAwjPYUEwnMObCGfguAd0Z3OrSTzHFmEcsisFv2A4vntL0BLPm_sVeemTG7XC0UkRC0ksgLBZKGAydqPqWldSjuX3HkwWZflf-l6s_ldS1EaUsGfOE8iS1-eSp_MdNK-wTxCrywiCEaHS0ee2mcUtIHr4ff-f_fx0as-Yp8Zb20FEjGBOI0q5Bxqvx_vauYifMT_TWWMd2mQxBujXYF5fAqrsGmHkxDXTzLVHClhHzwnNDDIkh6tzHzRHSTlUaKlyOjDr6_GVTSVYnBVEWvgvYMo8BloVDXgdTSAhiXYSjzIqgyhg_29bugS8zAb628bAoE_EYVhs3w
Content-Type: application/json