GET http://localhost:8080/teams

### Fetch all teams 

GET http://localhost:8080/api/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZjYzNmY2I2NDAzMjc2MGVlYjljMjZmNzdkNDA3YTY5NGM1MmIwZTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNzc0OTg3NSwidXNlcl9pZCI6ImtSVmRneUw4aWJNZXZ1cHBYeWZBa2plV1o1ZzIiLCJzdWIiOiJrUlZkZ3lMOGliTWV2dXBwWHlmQWtqZVdaNWcyIiwiaWF0IjoxNzI3NzQ5ODc1LCJleHAiOjE3Mjc3NTM0NzUsImVtYWlsIjoibUBtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtQG0uY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.G6cJ3sFA9M1Gu9WUZpUDG8j4Vu-MIFkaLZf6m5BwBZz6d04NTIZwvCsObVBlUoB6XVQdznZl6uHuJ_dIjSyN9Kgxxrx2QGtPHTP3FgrA7-IaZqEiF-XE38AtIB0z3IM-trWo-2tEX_GgMdDqPIoN-fXhmUNggZtZBJ9oBnfPTQ8yNe31T68fRvSXQ07y4n400MNXsnIJ-LA7vMnrU1sKzMxrT6oSpSaLSONJE-3g4HjRK1OGTs6M_lHBN3PSMO8vPLxLhZSMsxNRtvL0XQVLJ2OfTC-tq-XZ0JnSWN3AKzAr8P9Rg_p-jSk-JRAGTZ79puddy2TkQ6AJgYvaabWsHw
Content-Type: application/json

### Create Team

POST http://localhost:8080/api/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZjYzNmY2I2NDAzMjc2MGVlYjljMjZmNzdkNDA3YTY5NGM1MmIwZTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNzgzNDM2NywidXNlcl9pZCI6InNOMDFwWUs1ampobUVGYnFJTkFGTm5pRVFJaTEiLCJzdWIiOiJzTjAxcFlLNWpqaG1FRmJxSU5BRk5uaUVRSWkxIiwiaWF0IjoxNzI3ODQyNTcwLCJleHAiOjE3Mjc4NDYxNzAsImVtYWlsIjoicUBxLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJxQHEuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Z1m4kPB_5qEbkjyVZoOfE3bCyj0-JLtr2mJ8vrTxs0CX1ry1EwssSNF1pXchruGiHcotjjG-T5XqDS-nZsL1DxL0A-0mtFab1TlLLMZPsz8qO9uu2Q8Xqym-RTJjgeyMFXo1hbVKgGEuB3ScBUURizpvMk13mutTyKRSBjeFp55MdGTyEnmcFaHy-HKAqW-9e44eYyNJE_CTW6cXsIq3RDFGY-4zFwV4kxsN3HQXtetIabRoJQ68F3hmoJ9XuJK7S2Jmzt5434tU3kQZwAvleJy2bi0CP-MHqxX2CNq2VRIQti-NpBNnrWqQ4GUst2k0HseOWr7bLEzSkwsuksbFcQ
Content-Type: application/json

{
  "teamName": "Development Team",
  "members": [
    {
      "memberID": "66fb6f9d9c92ceb934b4975b",
      "firebaseID": "7AWrIVacnoXDVl3RdLx0CauhryS2",
      "color": "#FF5733"
    }
   
  ],
  "invitations": [
    "user1@example.com",
    "user2@example.com"
  ],
  "createdBy": {
    "memberID": "66fb6f9d9c92ceb934b4975b",
    "firebaseID": "7AWrIVacnoXDVl3RdLx0CauhryS2",
    "color": "#33FF57"
  },
  "shifts": []
}
### Fetch teams where user is a member
GET http://localhost:8080/api/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZjYzNmY2I2NDAzMjc2MGVlYjljMjZmNzdkNDA3YTY5NGM1MmIwZTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNzc1NDE0MCwidXNlcl9pZCI6IjdBV3JJVmFjbm9YRFZsM1JkTHgwQ2F1aHJ5UzIiLCJzdWIiOiI3QVdySVZhY25vWERWbDNSZEx4MENhdWhyeVMyIiwiaWF0IjoxNzI3NzU0MTQwLCJleHAiOjE3Mjc3NTc3NDAsImVtYWlsIjoibkBuLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJuQG4uY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.BJ5GCrjkfhEgEZkeoBqeiGqcpnczsl3ABOdWjjMoZlXkhXmjC4G5VSSc8mluT7wpuGG9Po3puSnIekEHMSb2G2I3pak6yb0IAcsmBQnXBPPsJT9f_PdHMpFw9IjhaU4b4mI14vzKTTnZYcatNdk6iwTCCjyec3-q1tyXDTwWt5xyke1qd-RX5PdQtm4Kmu1emYTXhuqw7gXMCPDe2azKTUBmyvm7VW-vuUB4W3bsq1pYBcuUJ90AjlqADAITYBz-GmMUqQ-2yfC3NNAkPUMiCJrkcHUiTVycPU2SftBHtRuaOpTqHMDas1keHlHCuuAPA-jpaVfnOByQkmwhEabK_w
Content-Type: application/json

###
