GET http://localhost:8080/teams

### Fetch all teams 

GET http://localhost:8080/api/teams/N1PnDQYt4OdFEscmhg9feMIbHpI2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImUwM2E2ODg3YWU3ZjNkMTAyNzNjNjRiMDU3ZTY1MzE1MWUyOTBiNzIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNjU0MzA2NywidXNlcl9pZCI6Ik4xUG5EUVl0NE9kRkVzY21oZzlmZU1JYkhwSTIiLCJzdWIiOiJOMVBuRFFZdDRPZEZFc2NtaGc5ZmVNSWJIcEkyIiwiaWF0IjoxNzI3MDU5NzkzLCJleHAiOjE3MjcwNjMzOTMsImVtYWlsIjoicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGF2b2wuc2xvdmFrMTk5NUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.RLlLq1ixjAnQOFAhEKyqjyvSMIsFj_KILz-qi8FUnKHK19O_iPk_nfKfgAAbXNkFr_Bfaq8MlnzVVTHUdjrj6-Ra1LFt8cf2FzA3jQJbWjaAWwEdjnYASgBoZjnOzatnlgAcvKdANUQc41TFajw3gVrQgNjP-qqIFgi0604v6BBpiJWWgUu4tRdLIxtnE4jO0kgd_JO2D65SF9mt9Sur3PwrekOjO5R8Pwd1k77xRJylbxrB85NJ5VjpxXFKX75rINWO7Mq2bw8VpqHxfp6rx5u8W9FB5_wLtK6EgNKJX1vnPEB2wBFkA8-dPMUXksEw1VnB4u1RMqisdLGW64Ol8A
{
   "teamId": "N1PnDQYt4OdFEscmhg9feMIbHpI2"
}
### Create Team

POST http://localhost:8080/api/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZjYzNmY2I2NDAzMjc2MGVlYjljMjZmNzdkNDA3YTY5NGM1MmIwZTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNzY2MDM3NSwidXNlcl9pZCI6IjBFTXNXcEZwaDFUN3NCeFp3U1pDSGpDeWhSeDIiLCJzdWIiOiIwRU1zV3BGcGgxVDdzQnhad1NaQ0hqQ3loUngyIiwiaWF0IjoxNzI3NjYwMzc1LCJleHAiOjE3Mjc2NjM5NzUsImVtYWlsIjoiYWFhQGFhYS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWFhQGFhYS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.ca6wmq-s3Xnoh__yotdf1EqWxUumV6hLIYsBAy6Y5z8vkjbqBY8pkakca2k0C6KxYcdqz4zzdKmmcP8ME83iEJ82tnlyGEBdei6vn6ec5Y3gthz-Orjkb_5cd8i9_F1X159t2Qy9r6TqvuBqs5uSBw6NlRM_zs_eMQcR7hw6Y8dtQCRIuiqI0sZ7MpBvM-j26t387AIX23EBCnl0c98Ee-qQ7gkOGgUPmeDB39EgLfLB5PgQ_uHNis7IcmzKSWPMme4uyxaxSsCNb4n7WtiXXIbgw6pJ0ls_XKgC-bdQyhirenaocJh3V04jkUX06dxaqM82gJ9gjEx8SeEA_vz6_g
Content-Type: application/json

{
   "teamName": "Team 22",
   "invitations": ["pavol@pavol.com", "pavol.slovak@gmail.com"],
   "members": [
     { "uid": "0EMsWpFph1T7sBxZwSZCHjCyhRx2", "color": "#FF5733" }
   ],
   "weekSchedule": [
        {
            "day": "Mon",
            "shifts": [
                {
                    "memberId": "0EMsWpFph1T7sBxZwSZCHjCyhRx2",
                    "startTime": "08:00",
                    "endTime": "12:00"
                },
                {
                    "memberId": "0EMsWpFph1T7sBxZwSZCHjCyhRx2",
                    "startTime": "12:00",
                    "endTime": "16:00"
                }
            ]
        }  
    ],
   "createdBy": { "id": "0EMsWpFph1T7sBxZwSZCHjCyhRx2" },
   "createdAt": "2021-07-22T15:00:00.000Z",
   "updatedAt": "2021-07-22T15:00:00.000Z"
}

### Fetch teams where user is a member
GET http://localhost:8080/api/teams
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjZjYzNmY2I2NDAzMjc2MGVlYjljMjZmNzdkNDA3YTY5NGM1MmIwZTMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3Rva2VtYW5hZ2VjYWxlbmRhci1kZXYiLCJhdWQiOiJzdG9rZW1hbmFnZWNhbGVuZGFyLWRldiIsImF1dGhfdGltZSI6MTcyNzY2MDM3NSwidXNlcl9pZCI6IjBFTXNXcEZwaDFUN3NCeFp3U1pDSGpDeWhSeDIiLCJzdWIiOiIwRU1zV3BGcGgxVDdzQnhad1NaQ0hqQ3loUngyIiwiaWF0IjoxNzI3NjYwMzc1LCJleHAiOjE3Mjc2NjM5NzUsImVtYWlsIjoiYWFhQGFhYS5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWFhQGFhYS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.ca6wmq-s3Xnoh__yotdf1EqWxUumV6hLIYsBAy6Y5z8vkjbqBY8pkakca2k0C6KxYcdqz4zzdKmmcP8ME83iEJ82tnlyGEBdei6vn6ec5Y3gthz-Orjkb_5cd8i9_F1X159t2Qy9r6TqvuBqs5uSBw6NlRM_zs_eMQcR7hw6Y8dtQCRIuiqI0sZ7MpBvM-j26t387AIX23EBCnl0c98Ee-qQ7gkOGgUPmeDB39EgLfLB5PgQ_uHNis7IcmzKSWPMme4uyxaxSsCNb4n7WtiXXIbgw6pJ0ls_XKgC-bdQyhirenaocJh3V04jkUX06dxaqM82gJ9gjEx8SeEA_vz6_g
Content-Type: application/json

###
